//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logbook
    {
        public int Logbook_Id { get; set; }
        public int Reader_Id { get; set; }
        public int Employee_Id { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Reader Reader { get; set; }
    }
}
