//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ReaderOrder_Id { get; set; }
        public int LineItem { get; set; }
        public int Book_Id { get; set; }
        public System.DateTime OrderDate { get; set; }
        public bool IsExpired { get; set; }
        public bool IsReturned { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual ReaderOrder ReaderOrder { get; set; }
    }
}
