//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int Day_Id { get; set; }
        public string DayName { get; set; }
        public int Employee_Id { get; set; }
        public string WorkTime { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
